name: pdv_windows
description: "Desafio técnico STI3"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependency_overrides:
  win32: 5.5.4

dependencies:
  flutter:
    sdk: flutter

  # state management
  flutter_mobx: ^2.2.1+1
  mobx: ^2.3.3+2
  provider: ^6.1.2

  # network
  dio: ^5.7.0

  # database
  hive: ^2.2.3
  path_provider: ^2.1.4
  get_it: ^7.7.0
  uuid: ^4.5.1

  # excel
  syncfusion_flutter_xlsio: ^27.1.50
  # language
  easy_localization: ^3.0.7

  # core utilities
  kartal: ^4.1.0
  internet_connection_checker_plus: ^2.5.2
  #  equatable: ^2.0.5
  #  onesignal_flutter: ^3.5.1

  # ui utilities
  #  animations: ^2.0.7
  fluent_ui: ^4.9.1
  flutter_spinkit: ^5.2.1
  syncfusion_flutter_charts: ^27.1.50
  graphic: ^2.5.0
  menu_bar: ^0.5.3
  google_fonts:
  auto_size_text: ^3.0.0
  another_flushbar: ^1.12.30
  connection_notifier: ^2.0.1

  cached_network_image: ^3.2.3
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.4
  extended_masked_text: ^2.3.1
  showcaseview: ^3.0.0

  architecture_theme:
    path: module/architecture_theme

dev_dependencies:
  flutter_test:
    sdk: flutter


  # core utilities
  build_runner: ^2.4.12
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  mobx_codegen: ^2.6.1
  hive_generator: ^2.0.1
  mockito: any

  # ui utilities
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  image_path: "assets/image/sti3-logo.png"
  windows:
    generate: true
    image_path: "assets/image/sti3-logo.png"
    icon_size: 48

flutter:
  uses-material-design: true

  assets:
    - assets/lang/
    - assets/image/
    - assets/svg/